"""add movies table, enforce user fields, add role enum

Revision ID: eac4d2055f33
Revises: 
Create Date: 2025-12-21 14:20:36.166567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac4d2055f33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_language', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.String(length=1000), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('poster_path', sa.String(length=1000), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('video', sa.Boolean(), nullable=False),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))

    userrole = sa.Enum('USER', 'ADMIN', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role DROP DEFAULT
    """)
    op.execute("""
        UPDATE users
        SET role = UPPER(role)
        WHERE role IS NOT NULL
    """)
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role
        TYPE userrole
        USING role::userrole
    """)
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role SET DEFAULT 'USER'
    """)

    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')

    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role DROP DEFAULT
    """)
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role
        TYPE VARCHAR(255)
    """)
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role SET DEFAULT 'USER'
    """)
    sa.Eтum(name='userrole').drop(op.get_bind(), checkfirst=True)

    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
